var PokiSDK = {
    init: function() { return Promise.resolve(); },
    gameLoadingStart: function() {},
    gameLoadingFinished: function() {},
    gameLoadingProgress: function() {},
    gameplayStart: function() {},
    gameplayStop: function() {},
    commercialBreak: function() { return Promise.resolve(); },
    rewardedBreak: function() { return Promise.resolve({ success: true }); },
    setDebug: function() {},
    isAdBlocked: function() { return false; },
    gameInteractive: function() {},
    customEvent: function() {},
    shareableURL: function() { return Promise.resolve(''); },
    displayAd: function() { return Promise.resolve(); },
    destroyAd: function() { return Promise.resolve(); },
    logError: function() {},
    happyTime: function() {},
    roundStart: function() {},
    roundEnd: function() {},
    sendHighscore: function() {}
};
